# Generated by Django 2.1.7 on 2019-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advising',
            old_name='date_posted',
            new_name='date_submitted',
        ),
        migrations.AlterField(
            model_name='advising',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
