# Generated by Django 2.1.7 on 2019-03-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='EMPLID',
            field=models.TextField(default='00000000'),
        ),
    ]
