# Generated by Django 2.1.7 on 2019-03-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_emplid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_Crystal',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_faculty',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='EMPLID',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
